/**
 * Build of the login extension: packages package.json + login.json + background.png into
 * dist/kwirth-login-<id>.tgz.
 *
 * It combines two precautions: a size cap on the background and atomic packaging.
 */
import { mkdirSync, existsSync, copyFileSync, statSync, rmSync, renameSync } from 'fs'
import { readFile } from 'fs/promises'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'
import { execSync } from 'child_process'

const __dir = dirname(fileURLToPath(import.meta.url))

// Dependency-free synchronous wait, to retry the rename.
const sleepSync = (ms) => { Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, ms) }

const pkg = JSON.parse(await readFile(join(__dir, 'package.json'), 'utf-8'))
const id = pkg.id ?? pkg.name.split('/').pop()

const distDir = join(__dir, 'dist')
mkdirSync(distDir, { recursive: true })

copyFileSync(join(__dir, 'package.json'), join(distDir, 'package.json'))
copyFileSync(join(__dir, 'login.json'), join(distDir, 'login.json'))

/*
    Background cap. The PNG travels in base64 inside a ConfigMap, and going over it does NOT break the
    installation: the login is installed half-way, without a background, and nobody notices until the
    page is opened. That is why the build fails here instead of letting it through.

    If it ever does not fit: re-encode to an 8-bit palette rather than cutting the dimensions. This
    login's background is line art generated by make-background.mjs and takes about 9 KB, so there
    is plenty of room.
*/
const CONFIGMAP_BACKGROUND_LIMIT = 600 * 1024

const bgSrc = join(__dir, 'background.png')
if (existsSync(bgSrc)) {
    const bytes = statSync(bgSrc).size
    if (bytes > CONFIGMAP_BACKGROUND_LIMIT) {
        console.error(`background.png is ${(bytes / 1024).toFixed(0)} KB and the cap is ${CONFIGMAP_BACKGROUND_LIMIT / 1024} KB ` +
            `(${(bytes * 4 / 3 / 1024).toFixed(0)} KB in base64, against an 800 KB limit in the ConfigMap).`)
        process.exit(1)
    }
    copyFileSync(bgSrc, join(distDir, 'background.png'))
}

/*
    Packaging goes to a temporary file OWNED BY THIS PROCESS, which is renamed over the target at the
    end.

    With the dev environment running there is a watch on this folder, so regenerating the background
    triggers ITS build at the same time as the one you launch by hand. Two `tar` processes writing
    the same .tgz overwrite each other and leave a valid archive followed by the tail of the other.
    It is treacherous: `tar -tzf` lists the three files correctly and only the exit code gives it
    away, so a broken bundle could be published without anyone noticing. The watch's guard does not
    help: it serializes within one process, not across processes.

    The rename is retried because the back may have the .tgz open (a dev login re-extracts the PNG
    from the archive on every background request) and returns EPERM/EBUSY.
*/
// Named after the package, like every other extension type: 'kwirth-<type>-<id>'.
const tgzName = `kwirth-login-${id}.tgz`
const tgzPath = join(distDir, tgzName)
const tmpName = `${id}.${process.pid}.tmp.tgz`
const tmpPath = join(distDir, tmpName)

execSync(`tar -czf ${tmpName} package.json login.json${existsSync(bgSrc) ? ' background.png' : ''}`, { cwd: distDir })

let renamed = false
for (let attempt = 0; attempt < 10 && !renamed; attempt++) {
    try {
        renameSync(tmpPath, tgzPath)
        renamed = true
    }
    catch (err) {
        if (attempt === 9) { rmSync(tmpPath, { force: true }); throw err }
        sleepSync(200)
    }
}

console.log(`Built dist/${tgzName}`)
