#!/bin/bash
export MAJOR=$(cat major)
export MINOR=$(cat minor)
export LEVEL=$(cat level)
export CURRENTVERSION=$MAJOR.$MINOR.$LEVEL

# docker image rm kwirth:latest
docker rmi jfvilasoutlook/kwirth:latest
docker pull jfvilasoutlook/kwirth:$CURRENTVERSION
docker tag jfvilasoutlook/kwirth:$CURRENTVERSION jfvilasoutlook/kwirth:latest
docker push jfvilasoutlook/kwirth:latest
