#!/bin/bash
export MAJOR=$(cat major)
export MINOR=$(cat minor)
export LEVEL=$(cat level)
export CURRENTVERSION=$MAJOR.$MINOR.$LEVEL

docker rmi kwirth:latest
docker rmi jfvilasoutlook/kwirth:latest
docker tag kwirth:$CURRENTVERSION kwirth:latest
docker tag kwirth:$CURRENTVERSION jfvilasoutlook/kwirth:latest
docker tag kwirth:$CURRENTVERSION jfvilasoutlook/kwirth:$CURRENTVERSION
docker push jfvilasoutlook/kwirth:latest
docker push jfvilasoutlook/kwirth:$CURRENTVERSION
