kwirth:
  kwirth:
    env:
      channelAlert: "true"
      channelEcho: "true"
      channelLog: "true"
      channelMetrics: "true"
      channelOps: "true"
      channelTrivy: "true"
      rootpath: /kwirth
