kwirth:
  config:
    channelAlert: "true"
    channelEcho: "false"
    channelLog: "true"
    channelMetrics: "true"
    channelOps: "true"
    channelTrivy: "false"
    rootpath: /kwirth
  image: jfvilasoutlook/kwirth:0.4.34