apiVersion: v1
kind: Service
metadata:
  name: {{ include "kwirth.fullname" . }}-kwirth-svc
  labels:
  {{- include "kwirth.labels" . | nindent 4 }}
spec:
  selector:
    app: kwirth
  ports:
    - name: kwirth-port
      protocol: TCP
      port: 3883
      targetPort: 3883
  type: ClusterIP
