apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kwirth.fullname" . }}-cr
  labels:
  {{- include "kwirth.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  - apps
  - rbac.authorization.k8s.io
  - networking.k8s.io
  - apiextensions.k8s.io
  - aquasecurity.github.io
  resources:
  - '*'
  verbs:
  - '*'
